services:
    Terminal42\LeadsBundle\Controller\Backend\LeadExportController:
        public: true
        arguments: ['@Terminal42\LeadsBundle\Exporter\ExporterFactory']

    Terminal42\LeadsBundle\Controller\Backend\LeadNotificationController:
        arguments: ['@Terminal42\LeadsBundle\Util\NotificationCenter']
        public: true

    Terminal42\LeadsBundle\Controller\Backend\LeadDetailsController:
        public: true
