services:
    Terminal42\LeadsBundle\EventListener\FormDataListener:
        tags:
        - { name: contao.hook, hook: processFormData }

    Terminal42\LeadsBundle\EventListener\UserNavigationListener:
        tags:
        - { name: contao.hook, hook: loadLanguageFile }
        - { name: contao.hook, hook: getUserNavigation }

    Terminal42\LeadsBundle\EventListener\SystemColumnRowListener:
        arguments: ['@Terminal42\LeadsBundle\Util\DataTransformer']
        tags: [{ name: kernel.event_listener, event: terminal42_leads.transform_row, method: onTransformRow, priority: 100 }]

    Terminal42\LeadsBundle\EventListener\TokenRowListener:
        arguments: ['@Terminal42\LeadsBundle\Util\DataTransformer']
        tags: [{ name: kernel.event_listener, event: terminal42_leads.transform_row, method: onTransformRow }]

    Terminal42\LeadsBundle\EventListener\DataContainer\LeadListener:
        public: true
        arguments:
            - '@Terminal42\LeadsBundle\Util\NotificationCenter'
            - '@Terminal42\LeadsBundle\Exporter\ExporterFactory'
            - '@router'
            - '@security.authorization_checker'

    Terminal42\LeadsBundle\EventListener\DataContainer\LeadExportListener:
        public: true
        arguments:
            - '@Terminal42\LeadsBundle\Exporter\ExporterFactory'
            - '@Terminal42\LeadsBundle\DataTransformer\DataTransformerFactory'
