services:
    Terminal42\LeadsBundle\EventListener\FormDataListener:
        tags:
        - { name: contao.hook, hook: processFormData }

    Terminal42\LeadsBundle\EventListener\UserNavigationListener:
        tags:
        - { name: contao.hook, hook: loadLanguageFile }
        - { name: contao.hook, hook: getUserNavigation }

    Terminal42\LeadsBundle\EventListener\DataContainer\LeadListener:
        public: true
        arguments:
            - '@Terminal42\LeadsBundle\Util\NotificationCenter'
            - '@Terminal42\LeadsBundle\Export\ExportFactory'

    Terminal42\LeadsBundle\EventListener\DataContainer\LeadExportListener:
        public: true
        arguments:
            - '@Terminal42\LeadsBundle\Export\ExportFactory'
