services:
    Terminal42\LeadsBundle\EventListener\DataContainer\LeadListener:
        public: true
        arguments:
            - '@Terminal42\LeadsBundle\Util\NotificationCenter'
            - '@Terminal42\LeadsBundle\Export\ExportFactory'
