services:
    _defaults:
        autoconfigure: true

    Terminal42\LeadsBundle\Command\ExportCommand:
        arguments:
            - '@contao.framework'
            - '@database_connection'
            - '@Terminal42\LeadsBundle\Export\ExportFactory'
            - '@filesystem'
        tags: ['console.command']

    Terminal42\LeadsBundle\Util\NotificationCenter:
        arguments: ['%kernel.bundles%']

    Terminal42\LeadsBundle\Export\ExportFactory:
        arguments: [!tagged terminal42_leads.export, '@database_connection']

    Terminal42\LeadsBundle\Export\CsvExport:
        arguments: ['@Terminal42\LeadsBundle\Util\ExportFile']

    Terminal42\LeadsBundle\Export\XlsExport:
        arguments: ['@Terminal42\LeadsBundle\Util\ExportFile']

    Terminal42\LeadsBundle\Export\XlsxExport:
        arguments: ['@Terminal42\LeadsBundle\Util\ExportFile']

    Terminal42\LeadsBundle\Util\ExportFile:
        arguments: ['@event_dispatcher']
